travis:
  secure:
    BINSTAR_TOKEN: u9Hg6Rs3YQ47wYTdwFsRIFGRwdOm4CFxzTx0n6I9H/S0Z5la6qDi911wEspQIjySSlnfnzc4C6TM4yf1jE+Kd+WILATQXghn8LCCwr8RPeX19sPcQPfzaSh2IMPxEh3PHjWjtB+QXbJF3i0OSKjSj9X+4svcmFy7LC3lIFTEy1TGKLtgloy3JIrhYmtpTVO/XZrESYd/wcVBZ7M7c8CnAY6bAne2Fk7Yshs/JWrZkkKKro6gva68Z5dVD25LQ009CwhQDKrJEzFtj7QU0RJahcTFxBXFkRnuRiiM+cv+ISdpytrS35dGIE1l+yhXNQyjxL3aYAn3H+27EF+xnFyXRc19EJ4AJBCx4s2f0ly9O0qhj0zID9FCWkFO51SWJerhI2orvgq46jM3aL835OjcdQ2Crs1Qk/ZvGybxrJuSCjmp3yK0tqOqCVgVeBepGRXwXxotnzvjw2ppDGotRJ3tVEqHz4lO8d21KIXmU/DHy2YELb4GscSF3s7SDJF+yMsXo91ELlqbkaSzm0bTIzXwrqceNxKQ7AjFXUzUnF9ST1DlZzNK7x259lS9BjNhz4kZ8IE96CWpwsM4dsh6fkMgYMfHiM1zwCei7Wm8JWSAXOCzMFzFlIBRmZon6NGth/ghuWsPKrMEoU0BVDILejnS0xxCO5Ekn5wWK/3BawAyYAM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
