travis:
  secure:
    BINSTAR_TOKEN: 1taREIJlw160+uMh6HSR4mAXRUZcIvkpH2eXdQ+ts/o3trERSk7KjszADyVeEkBDQCPAA72zpaXMUncmdr95c12sYx8HWpFBfgeMePkB/u0rkSAlQEsXSSCkUQA+MkTwTgKqfpeWcZlcySiN/Gd0Qf43GqdFLHXcajoDIHwI8cki5iq2wMnRC1o7Km2sbYWGv3luPW2LU2pjVOhldiurV2z6s9e7kOYRNiBmxsyXyTjsqWHAB/2Ag0y1LcE3q7eOo1YcD3HHRq3XdF43KbTKCi2W9AKnZa+b0iJjltkmJaUW6gh/lb/EODqA2wB65Y66JDJrQYbZXofefF3x3qNi5GdEO2jq0nz/pfaowPw6uhRMemo1Qi//JUffYdgDTw7/mSX+5C3AtEf8kb+uyOOUzLOrPH5If/pLa7t5rNfyJ4vnDh3XmDsfk7ctM4BraTKTT7Sg5eo0iOUtMmAcHQPKd64XCu6tTFBOQCZCJYfOJonDK99VdR+1P1dbN/DdBwCFSjSXRYahjy9xZJDhy4LVf6TYPVooZ5yx/vFymFECcsgcl6JiBtEtatAzYvhepgOGs6l6o4vdLpqiKbHecwPiUtc5phkHSVqRM1a9vvV+DyArJuEqQf1wR0QkohPlcmfizsRdRDGAHSUguM1l+IhDF/Cxv/hdMKznIPescY2i1fQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
