travis:
  secure:
    BINSTAR_TOKEN: mn6iVlXKnao46IJRJaxKU6SzRQKVUsXFD6cMx9OIco2LaCneXMbhsukx4/o6BMByJfd3VLCBywVv/Py2wyyK6oi69WwroelScYIoPdUMBKejvIhE8X2tdD/8FJGjnGFXCXpP1mCjSHeTkzxm2C9BZE7rI48cmKsbA1CFt7ScuYbB24PHTBFuuq1PT+2JTVPenN1kIfEONbqCnl6SN6v3v/7MwntKeE6bWUpHs9QYRWHPwLttqmHCXZAwaOnufWjnIA7gJuamfJPhG8Ue7lPTxp5JymZfX13QGGMNf6y0i8mTXGcoJJBfynl6A9/n1hsXaAzR609XlxQsmcs2ZgnuqBdY7hMk/7JVdzMeZOKrlclUUI/csWFkffXhMZ1PJZsuCeydM41pRRsvjm9nKMb9zfI4OHqyVGviHE2I+4+eK41lqwzO9GLLNclm5B7oLmFBKtRa+rIGsB7CoQvrJyxulpWGWsJiS4W03iAFl2ur1JShJAECOGhv61nR4E+i1VfpZ/McY0G9hmr870tTHqWG6n1XjQrqlGwBd4uBX1FgLfJmMiGEDP+vRoxpRQxUe9v9jQ/aI5dt71nW5KKm+NaKcAo+PgTYysHKr8P5V4P498ORo+p7hC2ofwB9Jf1j7Fa85Tb6P3TMpFQdCDJaZMjdAJUppSPjmbi4YCyvWteFHJo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
